### ISSUE TITLE
Incorrect poetry-core constraint

### ISSUE THREAD

**Issue by dminuoso** [gazpachoking/jsonref#49]
The pyproject.toml uses `[tool.poetry.group.dev.dependencies]` which is only available in poetry-core 1.2.0 or newer, which will cause errors like this one when using poetry 1.1.14 (which is default on NixOS 22.05)

We would get a better error if we constrained poetry-core to 1.2.0 or newer.
```
Processing /build/jsonref-1.0.1
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/nix/store/x2s1aqzhk6fkxv9a6fq50y81sib2avl4-python3.8-pip-22.0.4/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/nix/store/x2s1aqzhk6fkxv9a6fq50y81sib2avl4-python3.8-pip-22.0.4/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/x2s1aqzhk6fkxv9a6fq50y81sib2avl4-python3.8-pip-22.0.4/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/nix/store/j0fbyy5lgc58xxvwg2miv24ib8jpzha4-python3.8-poetry-core-1.0.8/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
    File "/nix/store/j0fbyy5lgc58xxvwg2miv24ib8jpzha4-python3.8-poetry-core-1.0.8/lib/python3.8/site-packages/poetry/core/factory.py", line 43, in create_poetry
      raise RuntimeError("The Poetry configuration is invalid:\n" + message)
  RuntimeError: The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
```

**Comment by gazpachoking** [comment]
Good call. I'll probably switch over to PDM when I get the chance (I like it a bit better, but only discovered it after I switched to Poetry), but this is an easy fix in the mean time.
