### ISSUE TITLE
Useful error reporting suppressed by less useful errors

### ISSUE THREAD

**Issue by quietlyconfident** [gazpachoking/jsonref#7]
I'm trying to get JsonRef to work and getting a traceback which I'll post below this comment.  Trying to make sense of it, it appears that half-way through, an error is trying to be thrown with the message "Unresolvable JSON Pointer. . . " from line 197 of jsonref.py, but then some other error is raised and this error never gets reported.

This makes it hard to debug, or at the very least, it is a bit of a tease.

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/jsonref.py", line 212, in __repr__
    return repr(self.__subject__)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/proxytypes.py", line 131, in __getattribute__
    return _oga(self, attr)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/proxytypes.py", line 209, in __subject__
    self.cache = super(LazyProxy, self).__subject__
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/proxytypes.py", line 195, in __subject__
    return self.callback()
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/jsonref.py", line 170, in callback
    result = self.resolve_pointer(base_doc, fragment)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/jsonref.py", line 197, in resolve_pointer
    self._error("Unresolvable JSON pointer: %r" % pointer, cause=e)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/erik/.virtualenvs/cr2/lib/python2.7/site-packages/jsonref.py", line 207, in _error
    cause=cause
JsonRefError
```

The JsonRefError is followed by a portion of the JSON object containing the refs I'm trying to resolve.

**Comment by gazpachoking** [comment]
You have an example I can test to dig deeper?

**Comment by mikeholler** [comment]
Here's an example (I'm having the same problem). I would really like it if the actual $ref URI value were displayed in the error output, at the very least. Ideally, both the $ref URI and call path (e.g., `myObject.3.otherObject.$ref -> #/badref`).

```
› python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jsonref, json
>>> from pprint import pprint
>>> jsonref.__version__
'0.1'
>>> data = jsonref.loads('{"real": [1, 2, 3, 4], "ref": {"$ref": "#/fake"}}')
>>> pprint(data)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pprint.py", line 59, in pprint
    printer.pprint(object)
  File "/usr/lib/python2.7/pprint.py", line 117, in pprint
    self._format(object, self._stream, 0, 0, {}, 0)
  File "/usr/lib/python2.7/pprint.py", line 140, in _format
    rep = self._repr(object, context, level - 1)
  File "/usr/lib/python2.7/pprint.py", line 226, in _repr
    self._depth, level)
  File "/usr/lib/python2.7/pprint.py", line 238, in format
    return _safe_repr(object, context, maxlevels, level)
  File "/usr/lib/python2.7/pprint.py", line 282, in _safe_repr
    vrepr, vreadable, vrecur = saferepr(v, context, maxlevels, level)
  File "/usr/lib/python2.7/pprint.py", line 323, in _safe_repr
    rep = repr(object)
  File "/usr/local/lib/python2.7/dist-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jsonref.py", line 212, in __repr__
    return repr(self.__subject__)
  File "/usr/local/lib/python2.7/dist-packages/proxytypes.py", line 131, in __getattribute__
    return _oga(self, attr)
  File "/usr/local/lib/python2.7/dist-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/proxytypes.py", line 209, in __subject__
    self.cache = super(LazyProxy, self).__subject__
  File "/usr/local/lib/python2.7/dist-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/proxytypes.py", line 195, in __subject__
    return self.callback()
  File "/usr/local/lib/python2.7/dist-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jsonref.py", line 159, in callback
    result = self.resolve_pointer(self.store[uri], fragment)
  File "/usr/local/lib/python2.7/dist-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jsonref.py", line 197, in resolve_pointer
    self._error("Unresolvable JSON pointer: %r" % pointer, cause=e)
  File "/usr/local/lib/python2.7/dist-packages/proxytypes.py", line 91, in wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/jsonref.py", line 207, in _error
    cause=cause
jsonref.JsonRefError
```

**Comment by gazpachoking** [comment]
```
Traceback (most recent call last):
  File "C:\Users\chase\PycharmProjects\jsonref\jsonref.py", line 195, in resolve_pointer
    document = document[part]
KeyError: 'fake'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\chase\AppData\Roaming\JetBrains\PyCharm2022.2\scratches\scratch.py", line 8, in <module>
    print(data)
  File "C:\Users\chase\PycharmProjects\jsonref\proxytypes.py", line 121, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\chase\PycharmProjects\jsonref\jsonref.py", line 213, in __repr__
    return repr(self.__subject__)
  File "C:\Users\chase\PycharmProjects\jsonref\proxytypes.py", line 163, in __getattribute__
    return _oga(self, attr)
  File "C:\Users\chase\PycharmProjects\jsonref\proxytypes.py", line 121, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\chase\PycharmProjects\jsonref\proxytypes.py", line 243, in __subject__
    self.cache = super(LazyProxy, self).__subject__
  File "C:\Users\chase\PycharmProjects\jsonref\proxytypes.py", line 121, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\chase\PycharmProjects\jsonref\proxytypes.py", line 227, in __subject__
    return self.callback()
  File "C:\Users\chase\PycharmProjects\jsonref\proxytypes.py", line 121, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\chase\PycharmProjects\jsonref\jsonref.py", line 158, in callback
    result = self.resolve_pointer(self.store[uri], fragment)
  File "C:\Users\chase\PycharmProjects\jsonref\proxytypes.py", line 121, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\chase\PycharmProjects\jsonref\jsonref.py", line 197, in resolve_pointer
    self._error("Unresolvable JSON pointer: %r" % pointer, cause=e)
  File "C:\Users\chase\PycharmProjects\jsonref\proxytypes.py", line 121, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\chase\PycharmProjects\jsonref\jsonref.py", line 202, in _error
    raise JsonRefError(
jsonref.JsonRefError: Error while resolving `#/fake`: Unresolvable JSON pointer: '/fake'
```

Here is the new traceback. For further troubleshooting, there are more attributes of `JsonRefError`s for introspection. I've now added [info in the docs](https://jsonref.readthedocs.io/en/latest/#when-things-go-wrong) about these.
