### ISSUE TITLE
Python 3.13 and json.dumps serializable issues

### ISSUE THREAD

**Issue by geographika** [gazpachoking/jsonref#70]
It seems as though I should have run into this issue on previous Python versions, so unsure what may have changed in Python 3.13 to trigger this. However, the following code worked fine in Python 3.10 after having loaded a schema with jsonref:

```
>>> print(json.dumps(deref_schema, indent=4))
```

However, when testing in Python 3.13 (with the same jsonref library version) it was throwing an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict is not JSON serializable
```

Interestingly, in Python 3.10 I could drill down to one of the objects and create the same error (but not when using `json.dumps` on the top level dictionary. 

```
>>> json.dumps(deref_schema["properties"]["filter"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python310\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "C:\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type dict is not JSON serializable
```

Fixed using the approaches outlined in #43, but this may be useful to anyone else running into issues in Python 3.13. 

Fixes for my project are at https://github.com/geographika/mappyfile/pull/215 and are to change:

```python
with open(fn, encoding="utf-8") as f:
    jsn_schema = jsonref.load(f, base_uri=base_uri)
```

To:

```python
with open(fn, encoding="utf-8") as f:
    jsn_schema = jsonref.load(f, base_uri=base_uri, lazy_load=False, proxies=False)
```

**Comment by geographika** [comment]
@gazpachoking - will close this as it is for info only. Thanks for creating jsonref.
